<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsMediaGallarySlidersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            // Galleries
            [
                'id' => 657,
                'name' => 'Can view galleries',
                'slug' => 'settings.galleries.list',
                'description' => null,
                'model' => 'Gallery',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 342,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 658,
                'name' => 'Can create galleries',
                'slug' => 'settings.galleries.create',
                'description' => null,
                'model' => 'Gallery',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 342,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 659,
                'name' => 'Can edit galleries',
                'slug' => 'settings.galleries.edit',
                'description' => null,
                'model' => 'Gallery',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 342,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 660,
                'name' => 'Can delete galleries',
                'slug' => 'settings.galleries.delete',
                'description' => null,
                'model' => 'Gallery',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 342,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 661,
                'name' => 'Can view gallery details',
                'slug' => 'settings.galleries.show',
                'description' => null,
                'model' => 'Gallery',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 342,
                'show_in_menu' => 'no',
            ],
            // Media
            [
                'id' => 662,
                'name' => 'Can view media',
                'slug' => 'settings.media.list',
                'description' => null,
                'model' => 'Media',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 343,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 663,
                'name' => 'Can create media',
                'slug' => 'settings.media.create',
                'description' => null,
                'model' => 'Media',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 343,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 664,
                'name' => 'Can edit media',
                'slug' => 'settings.media.edit',
                'description' => null,
                'model' => 'Media',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 343,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 665,
                'name' => 'Can delete media',
                'slug' => 'settings.media.delete',
                'description' => null,
                'model' => 'Media',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 343,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 666,
                'name' => 'Can view media details',
                'slug' => 'settings.media.show',
                'description' => null,
                'model' => 'Media',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 343,
                'show_in_menu' => 'no',
            ],
            // Sliders
            [
                'id' => 667,
                'name' => 'Can view sliders',
                'slug' => 'settings.sliders.list',
                'description' => null,
                'model' => 'Slider',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 344,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 668,
                'name' => 'Can create sliders',
                'slug' => 'settings.sliders.create',
                'description' => null,
                'model' => 'Slider',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 344,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 669,
                'name' => 'Can edit sliders',
                'slug' => 'settings.sliders.edit',
                'description' => null,
                'model' => 'Slider',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 344,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 670,
                'name' => 'Can delete sliders',
                'slug' => 'settings.sliders.delete',
                'description' => null,
                'model' => 'Slider',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 344,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 671,
                'name' => 'Can view slider details',
                'slug' => 'settings.sliders.show',
                'description' => null,
                'model' => 'Slider',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 344,
                'show_in_menu' => 'no',
            ],
            // Slider Slides
            [
                'id' => 672,
                'name' => 'Can view slider slides',
                'slug' => 'settings.slider-slides.list',
                'description' => null,
                'model' => 'SliderSlide',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 345,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 673,
                'name' => 'Can create slider slides',
                'slug' => 'settings.slider-slides.create',
                'description' => null,
                'model' => 'SliderSlide',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 345,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 674,
                'name' => 'Can edit slider slides',
                'slug' => 'settings.slider-slides.edit',
                'description' => null,
                'model' => 'SliderSlide',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 345,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 675,
                'name' => 'Can delete slider slides',
                'slug' => 'settings.slider-slides.delete',
                'description' => null,
                'model' => 'SliderSlide',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 345,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 676,
                'name' => 'Can view slider slide details',
                'slug' => 'settings.slider-slides.show',
                'description' => null,
                'model' => 'SliderSlide',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 345,
                'show_in_menu' => 'no',
            ],
            // Website Sections
            [
                'id' => 690,
                'name' => 'Can view website sections',
                'slug' => 'settings.website-sections.list',
                'description' => null,
                'model' => 'WebsiteSection',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 346,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 691,
                'name' => 'Can create website sections',
                'slug' => 'settings.website-sections.create',
                'description' => null,
                'model' => 'WebsiteSection',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 346,
                'show_in_menu' => 'yes',
            ],
            [
                'id' => 692,
                'name' => 'Can edit website sections',
                'slug' => 'settings.website-sections.edit',
                'description' => null,
                'model' => 'WebsiteSection',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 346,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 693,
                'name' => 'Can delete website sections',
                'slug' => 'settings.website-sections.delete',
                'description' => null,
                'model' => 'WebsiteSection',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 346,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 694,
                'name' => 'Can view website section details',
                'slug' => 'settings.website-sections.show',
                'description' => null,
                'model' => 'WebsiteSection',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 346,
                'show_in_menu' => 'no',
            ],
            [
                'id' => 695,
                'name' => 'Can reorder website sections',
                'slug' => 'settings.website-sections.sort-order',
                'description' => null,
                'model' => 'WebsiteSection',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'menu_id' => 346,
                'show_in_menu' => 'no',
            ],
        ];

        foreach ($permissions as $permission) {
            DB::table('permissions')->updateOrInsert(
                ['id' => $permission['id']],
                $permission
            );
        }
    }
}
