<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Web\WebsiteMenuItem;
use Illuminate\Support\Str;

class WebsiteMenuItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        WebsiteMenuItem::insert([
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 1,
                'parent_id' => null,
                'label' => 'Home',
                'url' => '#',
                'description' => '',
                'target' => '_self',
                'sort_order' => 0,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:08:28',
                'updated_at' => '2025-11-26 10:08:28',
                'deleted_at' => null,
            ],
            [
                'uuid' => (string) Str::uuid(),
                'website_menu_id' => 1,
                'parent_id' => null,
                'label' => 'Investment Opportunities',
                'url' => '#investment_opportunities',
                'description' => '',
                'target' => '_self',
                'sort_order' => 1,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:11:23',
                'updated_at' => '2025-11-26 10:11:23',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 1,
                'parent_id' => null,
                'label' => 'Cititzen Services',
                'url' => '#citizen_services',
                'description' => '',
                'target' => '_self',
                'sort_order' => 2,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:11:23',
                'updated_at' => '2025-11-26 10:11:23',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 1,
                'parent_id' => null,
                'label' => 'Transparency',
                'url' => '#transparency',
                'description' => '',
                'target' => '_self',
                'sort_order' => 3,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:11:23',
                'updated_at' => '2025-11-26 10:11:23',
                'deleted_at' => null,
            ],
            [
                'uuid' => (string) Str::uuid(),
                'website_menu_id' => 1,
                'parent_id' => null,
                'label' => 'Government Topics',
                'url' => '#government_topics',
                'description' => '',
                'target' => '_self',
                'sort_order' => 4,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:11:23',
                'updated_at' => '2025-11-26 10:11:23',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 1,
                'parent_id' => null,
                'label' => 'More Menu',
                'url' => '#',
                'description' => '',
                'target' => '_self',
                'sort_order' => 5,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:12:00',
                'updated_at' => '2025-11-26 10:12:00',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 2,
                'parent_id' => null,
                'label' => 'Privacy Policy',
                'url' => '#',
                'description' => '',
                'target' => '_self',
                'sort_order' => 1,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:11:23',
                'updated_at' => '2025-11-26 10:11:23',
                'deleted_at' => null,
            ],
            [
                'uuid' => (string) Str::uuid(),
                'website_menu_id' => 2,
                'parent_id' => null,
                'label' => 'Terms And Conditions',
                'url' => '#',
                'description' => '',
                'target' => '_self',
                'sort_order' => 4,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 10:11:23',
                'updated_at' => '2025-11-26 10:11:23',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 3,
                'parent_id' => null,
                'label' => 'Home',
                'url' => '#',
                'description' => '',
                'target' => '_self',
                'sort_order' => 0,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 13:46:52',
                'updated_at' => '2025-11-26 13:46:52',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 3,
                'parent_id' => null,
                'label' => 'Transparency',
                'url' => '#transparency',
                'description' => '',
                'target' => '_self',
                'sort_order' => 1,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 13:46:52',
                'updated_at' => '2025-11-26 13:46:52',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 3,
                'parent_id' => null,
                'label' => 'Government Topics',
                'url' => '#government_topics',
                'description' => '',
                'target' => '_self',
                'sort_order' => 2,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 13:46:52',
                'updated_at' => '2025-11-26 13:46:52',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 3,
                'parent_id' => null,
                'label' => 'Invesment Opportunities',
                'url' => '#invesment_opportunities',
                'description' => '',
                'target' => '_self',
                'sort_order' => 3,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 13:46:52',
                'updated_at' => '2025-11-26 13:46:52',
                'deleted_at' => null,
            ],
            [
                'uuid' =>  (string) Str::uuid(),
                'website_menu_id' => 3,
                'parent_id' => null,
                'label' => 'Citizen Services',
                'url' => '#citizen_services',
                'description' => '',
                'target' => '_self',
                'sort_order' => 4,
                'status' => 'active',
                'settings' => null,
                'created_at' => '2025-11-26 13:46:52',
                'updated_at' => '2025-11-26 13:46:52',
                'deleted_at' => null,
            ],
        ]);
    }
}
